services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: todo_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "25080:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=todo.settings

volumes:
  postgres_data:
